293 software erläuterung
Praxisprojekt2021/praxisprojekt pull request #113
Opened 2021-04-22 20:49 UTC by Antonio1730

## Bereich

* Frontend

## Typ

* Feature
* Design

## Code Review
- [ ] @NimsaJ150 / @jonathan112358 

## Funktionale Review
- [ ] @tomhinzmann @Timo-Buecher 

## Anmerkungen
Index.html can be ignored - prop to properly present the new functionality off-master.
As specified in the endpoints, the view can be accessed via "/about".

2021-04-22 20:50 UTC, Timo-Buecher commented
@Antonio1730 bitte Konflikte lösen

2021-04-23 21:09 UTC, Antonio1730 commented
Konflikte behoben.

2021-04-24 15:30 UTC, Timo-Buecher requested changes
Die Seite ist nicht erreichbar, Home war auch kaputt wegen einem Fehler in en.json (das hab ich schon gefixed. Bitte schnell drum kümmern und diesmal testen!

2021-04-24 15:30 UTC, Timo-Buecher commented
@Antonio1730 bitte achte auch nochmal drauf wie du deine Commits nennst, da fehlt immer die Branch-Nummer

2021-04-24 19:41 UTC, Timo-Buecher approved these changes
Passt für mich soweit, Code Review macht ja Jasmin.

2021-04-24 23:45 UTC, tomhinzmann requested changes
Ich würde mich freuen, wenn auch bei der /about Seite, analog zu den anderen Seiten, ein Breadcrumb vorhanden wäre :)

-> Rückfragen @NimsaJ150

2021-04-24 23:45 UTC, tomhinzmann commented on frontend/templates/index.html
> +        <a href="/about" class="navigation-links">What's Riskify?</a>
Text bitte noch auslagern

2021-04-24 23:45 UTC, tomhinzmann commented on frontend/templates/index.html
>      <div class="loader-text">Loading...</div>
Hier bitte einfach noch mit auslagern :)

2021-04-24 23:45 UTC, tomhinzmann commented on frontend/templates/info.html
> +    <a href="/" ><img src="{{ url_for('static', filename='images/logo.png') }}" loading="lazy" alt="" class ="logo">
Bitte konsistent über alle Seiten machen. Finde die Idee gut, deswegen würde ich vorschlagen, alle Riskify Logos zu Links zu machen.

2021-04-24 23:45 UTC, tomhinzmann commented on frontend/templates/info.html
> +            <img src="{{ url_for('static', filename='images/tutorial_dashboard.png') }}" style="width:100%" class="tutorial_image">
Inline CSS bitte entfernen

2021-04-24 23:45 UTC, tomhinzmann commented on frontend/templates/info.html
> +            <img src="{{ url_for('static', filename='images/Component1.png') }}" style="width:100%" class="tutorial_image">
Inline CSS bitte entfernen

2021-04-24 23:45 UTC, tomhinzmann commented on frontend/templates/info.html
> +            <img src="{{ url_for('static', filename='images/Component2.png') }}" style="width:100%" class="tutorial_image">
Inline CSS bitte entfernen

2021-04-24 23:45 UTC, tomhinzmann commented on frontend/templates/info.html
> +            <div class="numbertext">1 / 3</div>
Inline Text bitte auslagern

2021-04-24 23:45 UTC, tomhinzmann commented on frontend/templates/info.html
> +            <div class="numbertext">2 / 3</div>
Inline Text bitte auslagern

2021-04-24 23:45 UTC, tomhinzmann commented on frontend/templates/info.html
> +            <div class="numbertext">3 / 3</div>
Inline Text bitte auslagern

2021-04-24 23:45 UTC, tomhinzmann commented on frontend/templates/info.html
> +                <div class="text"><p data-i18n="Slide1"> </p></div>
```suggestion
                <div class="text"><p data-i18n="Slide1"></p></div>
```

2021-04-24 23:45 UTC, tomhinzmann commented on frontend/templates/info.html
> +                <div class="text"><p data-i18n="Slide2"> </p></div>
```suggestion
                <div class="text"><p data-i18n="Slide2"></p></div>
```

2021-04-24 23:45 UTC, tomhinzmann commented on frontend/templates/info.html
> +                <div class="text"><p data-i18n="Slide3"> </p></div>
```suggestion
                <div class="text"><p data-i18n="Slide3"></p></div>
```

2021-04-24 23:45 UTC, tomhinzmann commented on frontend/static/js/info.js
> +}
```suggestion
}

```

Bitte Leerzeile hinzufügen

2021-04-24 23:45 UTC, tomhinzmann commented on frontend/static/js/info.js
> + * **/
Bitte nochmals die Definition unserer docstrings anschauen

2021-04-24 23:45 UTC, tomhinzmann commented on frontend/static/js/info.js
> +// Thumbnail image functionality
Bitte nochmals die Definition unserer docstrings anschauen

2021-04-24 23:45 UTC, tomhinzmann commented on frontend/static/js/info.js
> +function plusSlides(n) {
Bitte nochmals die Definition unserer docstrings anschauen

2021-04-25 08:52 UTC, Timo-Buecher commented
@Antonio1730 kümmerst du dich drum?

2021-04-25 17:38 UTC, Antonio1730 commented on frontend/templates/index.html
> +        <a href="/about" class="navigation-links">What's Riskify?</a>
done

2021-04-25 17:39 UTC, Antonio1730 commented on frontend/templates/index.html
>      <div class="loader-text">Loading...</div>
done

2021-04-25 17:43 UTC, Antonio1730 commented on frontend/templates/info.html
> +            <img src="{{ url_for('static', filename='images/Component1.png') }}" style="width:100%" class="tutorial_image">
done

2021-04-25 17:43 UTC, Antonio1730 commented on frontend/templates/info.html
> +            <img src="{{ url_for('static', filename='images/tutorial_dashboard.png') }}" style="width:100%" class="tutorial_image">
done

2021-04-25 17:48 UTC, Antonio1730 commented on frontend/static/js/info.js
> + * **/
done

2021-04-25 17:49 UTC, Antonio1730 commented on frontend/templates/info.html
> +    <a href="/" ><img src="{{ url_for('static', filename='images/logo.png') }}" loading="lazy" alt="" class ="logo">
done

2021-04-25 19:47 UTC, Timo-Buecher approved these changes
Getestet, Code Review steht aus.

2021-04-25 20:19 UTC, sascha7777 commented on frontend/static/css/Info_styles.css
> +}
```suggestion
}

```

2021-04-25 20:23 UTC, sascha7777 approved these changes
Code passt, ein Bug entdeckt, der als separater Issue angelegt wird.

2021-04-25 20:49 UTC, Timo-Buecher approved these changes

2021-04-25 20:50 UTC, merged