I48 gleiche metrik namen
Praxisprojekt2021/praxisprojekt pull request #144
Opened 2021-04-26 18:04 UTC by Sofie273

## Bereich
* Backend
   - Database-Handler
* Database

## Typ

* Testfinding / Bug

## Code Review
- [ ] @jonathan112358

## Funktionale Review
- [ ] @Timo-Buecher 

## Anmerkungen
constraint wurde in unserer neo4j datenbank bereits gesetzt. Zum testen der query bitte lokale instanz benutzen, bzw im db menü die constraint hiermit entfernen: Drop CONSTRAINT ON (n:Metric) ASSERT n.name IS UNIQUE und dann über create metrics hinzufügen

2021-04-27 15:17 UTC, Timo-Buecher commented
Verstehe ich es richtig: Du hast die Funktion schon ausgeführt, wenn wir das aber jetzt auf eine andere DB portieren dann müsste die Funktion wieder ausgeführt werden?

Ich würde folgendes Vorschlagen, in der create_metrics.py eine Funktion zu schreiben, die zunächst den Constraint löscht, dann den Constraint wieder hinzufügt und dann die Metriken anlegt. 

Was sagt ihr dazu, @NimsaJ150 @jonathan112358 @Sofie273 

Ggf. kann man das delete auch weglassen, ich finde es nur schöner wenn das quasi "sauber" aufgesetzt wird. Man müsste nur halt testen was passiert wenn die nicht existieren ob dann ein Fehler fliegt. Wenn man es weglässt muss man prüfen ob ein Fehler fliegt wenn die bereits existieren.

2021-04-27 15:23 UTC, Sofie273 commented
@Timo-Buecher Ja ich kann auch eine delete funktion aufsetzen. Weiß jetzt aus dem Stand nicht ob das löschen einen fehler werfen würde und dann die creation abbricht, wenn man versucht eine constraint zu löschen die es nicht gibt.

Die constraint ist schon gesetzt aktuell und wird in create metrics beim ausführen der datei auch gesetzt.

2021-04-29 15:04 UTC, Sofie273 commented
> Verstehe ich es richtig: Du hast die Funktion schon ausgeführt, wenn wir das aber jetzt auf eine andere DB portieren dann müsste die Funktion wieder ausgeführt werden?
> 
> Ich würde folgendes Vorschlagen, in der create_metrics.py eine Funktion zu schreiben, die zunächst den Constraint löscht, dann den Constraint wieder hinzufügt und dann die Metriken anlegt.
> 
> Was sagt ihr dazu, @NimsaJ150 @jonathan112358 @Sofie273
> 
> Ggf. kann man das delete auch weglassen, ich finde es nur schöner wenn das quasi "sauber" aufgesetzt wird. Man müsste nur halt testen was passiert wenn die nicht existieren ob dann ein Fehler fliegt. Wenn man es weglässt muss man prüfen ob ein Fehler fliegt wenn die bereits existieren.

wenn die delete constraint funktionversucht eine constraint zu löschen die es nicht gibt, wirft sie einen fehler... müsste man über das kommende db error handling abfangen um dann den rest auszuführen, die funktion wäre jetzt implementiert

2021-04-30 20:15 UTC, Timo-Buecher submitted a review, later dismissed

2021-04-30 20:25 UTC, Timo-Buecher submitted a review, later dismissed

2021-05-02 11:41 UTC, jonathan112358 requested changes
In den geänderten Files fehlen leider überall am Ende noch die neuen Zeilen, was eine Anforderung gemäß PEP8 ist. 
Außerdem sollten die Funktionen in create_metrics bitte aaskommentiert sein, sodass diese keiner zufällig ausführt. So wurde das auch bisher in der Datei gehandhabt.

2021-05-02 17:14 UTC, jonathan112358 approved these changes
Sieht für mich jetzt fein aus, danke!

2021-05-03 19:32 UTC, Timo-Buecher approved these changes

2021-05-03 19:32 UTC, merged