I128: Alles fixed
Praxisprojekt2021/praxisprojekt pull request #153
Opened 2021-04-29 23:06 UTC by twonkos

## Bereich

* Frontend

## Typ

* Feature
* Testfinding / Bug

## Code Review
- [ ] @NimsaJ150 / @jonathan112358 / @sascha7777

## Funktionale Review
- [ ] @Timo-Buecher 

## Anmerkungen

**Änderungen:**

Prozessansicht:
- Hover auf help icon -> Wie bei den Tabellen Headern wird ein custom popup angezeigt
- Hover auf target average -> Min max wird popup mit min & max angezeigt falls es eins gibt, wenn nur min oder nur max dann entsprechend nur min oder max, wenn beides nicht in den attributen ist dann nichts

Komponentenansicht:
- Hover auf help icon -> Custom popup wird angezeigt
- Hover auf metric input -> Min max wird popup mit min & max angezeigt falls es eins gibt, wenn nur min oder nur max dann entsprechend nur min oder max, wenn beides nicht in den attributen ist dann nichts

-> Popups werden instant angezeigt

Closes #128

2021-04-30 20:32 UTC, Timo-Buecher submitted a review, later dismissed
Hammer Features, gefällt mir echt gut :)

2021-05-01 18:12 UTC, sascha7777 requested changes
<img width="1096" alt="2021-05-01 20_09_48-Component - Persönlich – Microsoft​ Edge" src="https://user-images.githubusercontent.com/43936809/116791293-91fed200-aab9-11eb-9ef6-ea2fd04bd28b.png">


Bei Komponenten kommt das Popup sehr weit weg vom eigentlichen Feld - ist das gewoll?

2021-05-01 18:34 UTC, twonkos commented
> <img alt="2021-05-01 20_09_48-Component - Persönlich – Microsoft​ Edge" width="1096" src="https://user-images.githubusercontent.com/43936809/116791293-91fed200-aab9-11eb-9ef6-ea2fd04bd28b.png">
> 
> Bei Komponenten kommt das Popup sehr weit weg vom eigentlichen Feld - ist das gewoll?

Das sollte nicht passieren, ich hab dafür eigentlich ein fix eingebaut gehabt, schaue es mir eben an

2021-05-01 18:48 UTC, twonkos commented
> <img alt="2021-05-01 20_09_48-Component - Persönlich – Microsoft​ Edge" width="1096" src="https://user-images.githubusercontent.com/43936809/116791293-91fed200-aab9-11eb-9ef6-ea2fd04bd28b.png">
> 
> Bei Komponenten kommt das Popup sehr weit weg vom eigentlichen Feld - ist das gewoll?

Das kommt bei mir nicht so extrem wie bei dir, ich hab es jetzt aber noch mal um 24% nach links geschoben, schau mal ob es für dich so passt

2021-05-01 18:50 UTC, sascha7777 commented
<img width="548" alt="2021-05-01 20_50_03-Component - Persönlich – Microsoft​ Edge" src="https://user-images.githubusercontent.com/43936809/116792099-e6f11700-aabe-11eb-94ad-d819fa6eb508.png">

sieht jetzt gut aus

2021-05-01 18:53 UTC, sascha7777 approved these changes

2021-05-01 18:55 UTC, Timo-Buecher approved these changes

2021-05-01 18:59 UTC, merged

2021-05-02 15:07 UTC, NimsaJ150 commented
@twonkos @Timo-Buecher @sascha7777 

"Hover auf target average -> Min max wird popup mit min & max angezeigt falls es eins gibt, wenn nur min oder nur max dann entsprechend nur min oder max, wenn beides nicht in den attributen ist dann nichts"

Warum nicht auch bei target min und target max in der Prozessansicht? Diese haben auch min und max Werte. Aus welchem Grund wird hier nichts zum Hovern angezeigt?