I136: We renamend component_count and edited the metrics_dict into th…
Praxisprojekt2021/praxisprojekt pull request #156
Opened 2021-05-01 15:09 UTC by CorvinFassbender

…e JSON_objects_definitions.py

## Bereich

*Doku

## Typ

* Testfinding / Bug

## Code Review
- [ ] @NimsaJ150 / @jonathan112358

## Funktionale Review
- [ ] @Timo-Buecher 
## Anmerkungen

2021-05-02 08:07 UTC, Timo-Buecher approved these changes
passt für mich

2021-05-02 11:58 UTC, jonathan112358 requested changes
Also grds. finde ich die Anpassungen gut. 
- Allerdings ist es nicht nötig für die Doku 125 Zeilen mit Metriken zu befüllen. Das macht den Code nur unübersichtlich. Im restlichen Teil der Doku haben wir daher immer nur einen Teil genannt und mit "# ..." kenntlich gemacht, dass es länger ist.
- Bitte macht außerdem die Überschrift gleich zum Rest. Damit meine ich eine Leerzeile über der Überschrift und keine drunter.

2021-05-04 20:59 UTC, Timo-Buecher approved these changes

2021-05-04 20:59 UTC, Timo-Buecher commented
@jonathan112358 hab es gefixed damit es jetzt mal auf dem master kommt. schau nochmal drüber ob es jetzt für dich passt

2021-05-05 19:11 UTC, jonathan112358 approved these changes

2021-05-05 19:11 UTC, merged