I109 Auslagern von Tabellenheader Helper Texten (neu)
Praxisprojekt2021/praxisprojekt pull request #157
Opened 2021-05-01 20:12 UTC by N3R1K

## Bereich
* Frontend

## Typ
* Sonstiges: Cleanup

## Code Review
- [ ] @NimsaJ150 

## Funktionale Review
- [ ] @tomhinzmann

## Anmerkungen
Ersetzt PR: https://github.com/Praxisprojekt2021/praxisprojekt/pull/122
Von Issue: https://github.com/Praxisprojekt2021/praxisprojekt/issues/109
Fix von: "Tabellen Header Helper Texte auf der Prozess Ansicht stehen derzeit statisch im Code und sollten in ein entsprechendes (vermutlich neues) json file ausgelagert werden."

2021-05-02 11:48 UTC, jonathan112358 reviewed
Bei mir funktionieren die Änderungen leider nicht. Es wird zwar nirgends ein Fehler geschmissen, allerdings erhalte ich beim Hovern über die Überschriften keine Erklärungstexte mehr. Daher gehe ich von einem Fehler aus.

2021-05-02 12:45 UTC, N3R1K commented
@jonathan112358 Oh, hatte beim merge was übersehen, jetzt sollte es passen.

2021-05-02 14:35 UTC, jonathan112358 submitted a review, later dismissed
Bin in dem Code nicht super drin @tomhinzmann oder @NimsaJ150 . Es wäre daher super, wenn einer von euch in den kurz reinguckst. Funktional sieht es bei mir aber gut aus.

2021-05-02 17:26 UTC, NimsaJ150 requested changes
@N3R1K passt für mich codetechnisch soweit. Ich finde den Datei und Variablen Namen nur etwas irreführend, da Features ja eigentlich unsere Merkmale sind. Daher wäre vielleicht TableHeaderInfo oder etwas in die Richtung sinnvoller als Datei und Variablen Namen :)

2021-05-02 18:20 UTC, N3R1K commented
@NimsaJ150 achso verstehe, habe jetzt das wording angepasst. :)

2021-05-02 20:08 UTC, NimsaJ150 submitted a review, later dismissed

2021-05-03 14:45 UTC, tomhinzmann approved these changes

2021-05-03 14:45 UTC, NimsaJ150 approved these changes

2021-05-03 14:45 UTC, merged