I132 about neues design übernehmen
Praxisprojekt2021/praxisprojekt pull request #159
Opened 2021-05-01 20:17 UTC by Antonio1730

## Bereich

* Frontend

## Typ

* Design

## Code Review
- [ ] @NimsaJ150 / @jonathan112358 / @sascha7777

## Funktionale Review
- [ ] @Timo-Buecher @tomhinzmann 

## Anmerkungen

2021-05-02 08:27 UTC, Timo-Buecher approved these changes

2021-05-02 11:34 UTC, jonathan112358 reviewed
Ich glaube hier ist was schief gegangen. Bei mir sind zumindest noch die alten Bilder drin.

2021-05-03 19:39 UTC, sascha7777 requested changes
Wie @jonathan112358 schon angemerkt hat, sehe ich auch noch die alten Bilder.

![image](https://user-images.githubusercontent.com/43936809/116924338-08393b00-ac58-11eb-86ff-f33eb88456f7.png)

2021-05-04 20:10 UTC, Antonio1730 commented
@jonathan112358 @sascha7777 hier ging es nicht um das updaten der Bilder - das ist 127. Hier war lediglich der Background anzupassen, sodass dieser mit den anderen Seiten vom Style übereinstimmt.

2021-05-04 20:11 UTC, sascha7777 approved these changes

2021-05-04 20:11 UTC, sascha7777 commented
> @jonathan112358 @sascha7777 hier ging es nicht um das updaten der Bilder - das ist 127. Hier war lediglich der Background anzupassen, sodass dieser mit den anderen Seiten vom Style übereinstimmt.

Approved

2021-05-04 20:14 UTC, merged