98 de.json
Praxisprojekt2021/praxisprojekt pull request #16
Opened 2021-03-16 16:57 UTC by lucab99

## Bereich

* Frontend

## Typ

* Feature

## Code Review
- [ ] @NimsaJ150 / @jonathan112358

## Funktionale Review
- [ ] @NimsaJ150 

## Anmerkungen

2021-03-17 20:35 UTC, jonathan112358 requested changes
Zwei Sachen meinerseits. 
1. das file de.json liegt jetzt sehr verschachtelt in dem Ordner. Ist das so gewollt, oder könnten man das nicht einfach im content Ordner ablegen?
2. die Änderungen im html file müssen nochmal überarbeitet werden, da das file zwischenzeitlich angepasst wurde.

2021-03-18 17:55 UTC, lucab99 commented
@jonathan112358 Danke, ich habe deine beiden Bemerkungen jetzt eingearbeitet.

2021-03-18 20:54 UTC, NimsaJ150 commented on frontend/templates/index.html
> +        <label for="number-2" data-i18n="number-2">Number 2</label>
```suggestion
        <label for="number-2" data-i18n="number-2"></label>
```

2021-03-18 20:57 UTC, NimsaJ150 approved these changes
Nur nochmal zur Anmerkung :) Passt aber soweit für mich, auch ohne das nochmal zu ändern (kommt in Zukunft ja eh raus). Danke für deine Mühe!

2021-03-18 21:02 UTC, jonathan112358 approved these changes
Super, danke für die Anpassungen

2021-03-18 21:02 UTC, merged