I125 about skalierung
Praxisprojekt2021/praxisprojekt pull request #160
Opened 2021-05-01 20:18 UTC by Antonio1730

## Bereich

* Frontend

## Typ

* Testfinding / Bug

## Code Review
- [ ] @NimsaJ150 / @jonathan112358 / @sascha7777

## Funktionale Review
- [ ] tba @Timo-Buecher @tomhinzmann 

## Anmerkungen

2021-05-02 08:30 UTC, Timo-Buecher approved these changes

2021-05-02 11:30 UTC, jonathan112358 requested changes
Ich bin mir nicht sicher, ob ich das Issue korrekt verstehe. Ich sehe zumindest keine Fehler mit der Skalierung des Textes, allerdings ist mir was anderes kleines aufgefangen. Es wäre schön, wenn wir das in dem PR erledigt bekommen:
- Die Namen für unsere Erklärungsseite stimmen nicht überein: "What we're about" und "What's Riskify"
- In der "Menüleiste" oben ist im HomeScreen das Home grün markiert und der Pfeil zeigt wie folgt: "Home <". Sobald man allerdings drüberhovert dreht er sich auf Whats Riskify.
- Wenn man auf der Erklärungsseite ist, funktioniert das allerdings anders. Dort zeigt der Pfeil standardmäßig auf "What we're about" und dreht sich nicht sobald man drüberhovert. Das ist also unterschiedlich. des Weiteren ist der Name "What we're about" hier nicht grün markiert, wie Home auf dem Homescreen.
Ich würde euch bitten die drei Sachen anzupassen.

https://user-images.githubusercontent.com/74042443/116811592-83143000-ab4a-11eb-88c7-030371d9de79.mov

2021-05-02 12:51 UTC, Antonio1730 commented
@jonathan112358 kann ich damit umsetzen

2021-05-03 19:33 UTC, Timo-Buecher commented
@Antonio1730 wann ist das circa erledigt?

2021-05-04 20:08 UTC, Antonio1730 commented
Sollte passen @jonathan112358 ich kann aus irgend einem Grund nicht testen - ladescreen löst sich nicht auf

2021-05-06 20:46 UTC, Antonio1730 commented
bitte testet das @Timo-Buecher @jonathan112358 bei mir löst sich die Index Seite nicht auf sondern ist dauerhaft im loading mode. Die Änderungen auf der Index Seite entsprechen jetzt dem Stand der Anderen - daran sollte es liegen.

2021-05-07 16:16 UTC, Timo-Buecher requested changes
Bitte mit @twonkos sprechen und die Sklarierung GENAU so umsetzen wie auf den anderen Seiten. Den z.B. skaliert der Text nicht richtig (wird nicht kleiner)

2021-05-07 16:16 UTC, Timo-Buecher commented on frontend/templates/index.html
> +        <a href="#" class="navigation-links" data-i18n="about"></a>
Das href ist falsch, bitte anpassen. Man wird nicht auf die About Seite geleitet

2021-05-10 20:31 UTC, closed without merging