I missing min / max values
Praxisprojekt2021/praxisprojekt pull request #172
Opened 2021-05-03 18:28 UTC by N3R1K

## Bereich

## Typ
* Sonstiges enhancement

## Code Review
- [ ] @NimsaJ150 / @jonathan112358 / @sascha7777

## Funktionale Review
- [ ] @Timo-Buecher 

## Anmerkungen

2021-05-03 19:45 UTC, Timo-Buecher approved these changes
getestet, hab es nochmal etwas umgebaut. so braucht man nur eine if anstatt drei

2021-05-03 20:23 UTC, sascha7777 requested changes

2021-05-03 20:23 UTC, sascha7777 commented on frontend/static/js/process-editor.js
>          const inputs = document.getElementsByName(element);
Kann die if nicht vor die Schleife gezogen werden - muss ja nicht für jedes mal wieder geprüft werden, oder?

```suggestion

if (element === 'target-average' || element === 'target-minimum' || element === 'target-maximum') {
        const inputs = document.getElementsByName(element);
        for (let i = 0; i < inputs.length; i++) {
             helper.addMinMaxPopup(inputs[i]);
        }
```

2021-05-03 20:26 UTC, sascha7777 requested changes

2021-05-03 20:26 UTC, sascha7777 commented on frontend/static/js/process-editor.js
>              }
Können wir die if nicht sogar aus der Schleife raus nehmen?

```
if (element === 'target-average' || element === 'target-minimum' || element === 'target-maximum') {
        const inputs = document.getElementsByName(element);
        for (let i = 0; i < inputs.length; i++) {
             helper.addMinMaxPopup(inputs[i]);
        }``
```

2021-05-04 20:06 UTC, sascha7777 commented on frontend/static/js/process-editor.js
>              }
Habs korrigiert

2021-05-04 20:07 UTC, sascha7777 submitted a review, later dismissed

2021-05-04 20:11 UTC, NimsaJ150 commented
Wozu brauchen wir die if Abfrage denn überhaupt?

2021-05-05 18:51 UTC, Timo-Buecher commented
@NimsaJ150 hast recht gehabt, hab es gefixed.

2021-05-05 18:51 UTC, Timo-Buecher submitted a review, later dismissed

2021-05-05 18:53 UTC, Timo-Buecher approved these changes

2021-05-05 19:15 UTC, sascha7777 approved these changes

2021-05-05 19:22 UTC, merged