391 issue texte abgeschnitten
Praxisprojekt2021/praxisprojekt pull request #181
Opened 2021-05-07 14:32 UTC by Eren04

## Bereich

* Frontend

## Typ

* Testfinding / Bug

## Code Review
- [ ] @NimsaJ150 / @jonathan112358 / @sascha7777

## Funktionale Review
- [ ] @prinzpaul 

## Anmerkungen

2021-05-09 19:26 UTC, sascha7777 approved these changes

2021-05-09 19:30 UTC, sascha7777 requested changes
![image](https://user-images.githubusercontent.com/43936809/117584505-b12ade80-b10d-11eb-8f46-610b8a5557c6.png)

Das sieht falsch aus.

2021-05-10 20:09 UTC, Eren04 commented
@sascha7777 wehe du machst das Ding wieder kaputt!
Schau mal bitte rein sollte jetzt hoffentlich funktionieren. 

@Timo-Buecher @NimsaJ150 hab das Ding im Inkognito Modus getestet, den Master reingemerged und alles lief gut.
Wenn irgendwas ist, dann verstehe ich Github einfach nicht :D

2021-05-11 08:09 UTC, Timo-Buecher approved these changes
Funktionalität passt

2021-05-11 12:53 UTC, merged