167: DB Init Skript und Create Query Doku
Praxisprojekt2021/praxisprojekt pull request #20
Opened 2021-03-18 15:27 UTC by Timo-Buecher

## Bereich
* Database

## Typ
* Sonstiges Doku/Vorlage und init-Skript

## Code Review
- [ ] @NimsaJ150 / @jonathan112358

## Funktionale Review
- [ ] @Nico3001 / @lucabloe

## Anmerkungen
Funktionale Review durch Nicolas und Luca, da diese Cypher kennen.
Bitte schaut euch die Queries an und prüft ob diese Sinnhaft sind.

2021-03-18 21:01 UTC, jonathan112358 commented
@NimsaJ150 Kennst du dich mit dieser .cypher Datei aus. Sonst würde ich mich einlesen, kann das nämlich nicht wirklich inhaltlich reviewen

2021-03-18 21:15 UTC, NimsaJ150 commented
Tue ich leider nicht, du musst aber ja nur schauen, ob das Code technisch (Leerzeilen usw.) passt. Timo meinte ja schon Luca und Nicolas kennen sich mit Cypher aus und schauen sich das funktional/inhaltlich an.

2021-03-18 21:25 UTC, Timo-Buecher commented
Es gibt für Cypher leide keine Richtlinie wie man Code richtig formatiert... daher könnt ihr garnicht viel prüfen. Inhaltlich schauen ja Nicolas und Luca drüber.

2021-03-19 12:29 UTC, lucab99 requested changes
@Timo-Buecher Ich habe den PR jetzt gereviewed. Im Großen und Ganzen passt es für mich, aber ich habe noch zwei kleine Bemerkungen hinzugefügt.

2021-03-19 12:29 UTC, lucab99 commented on database/init_db.cypher
> +  (`Oracle DB`:Component {name:               'Oracle Datenbank', description: 'Kudendatenbank',
Rechtschreibfehler im Wort "Kundendatenbank"

--> korrekte Codezeile:
`  (`Oracle DB`:Component {name:               'Oracle Datenbank', description: 'Kundendatenbank',
`

2021-03-19 12:29 UTC, lucab99 commented on database/init_db.cypher
> +                                                  description: 'Durchschnittliche Ausfallzeit in Minuten'})
Meiner Meinung nach fehlt da noch eine Angabe bei der Beschreibung der Ausfallzeit, nämlich ob die in Minuten pro Tag oder Minuten pro Jahr angegeben ist.

Vorschlag:
`                                                  description: 'Durchschnittliche Ausfallzeit in Minuten pro Tag'})
`

2021-03-19 12:59 UTC, lucab99 approved these changes

2021-03-19 13:01 UTC, lucabloe approved these changes

2021-03-19 13:40 UTC, nicolasschmid0 commented
Bei der Erstellung von Komponenten könnte der zugehörige Prozess noch bspw. im "name" Attribut vermerkt werden, um später bei mehreren Prozessen getrennte Instanzen von "gleichen" Komponenten besser zuordnen zu können.

2021-03-20 09:03 UTC, jonathan112358 approved these changes
Da Luca approved hat gebe ich auch frei. Dann können wir den Request schließen. Konnte mich in das Thema selbst leider noch nicht tiefer einlesen. Werde ich jetzt am WE machen

2021-03-20 09:03 UTC, merged