209 testfinding nacharbeit
Praxisprojekt2021/praxisprojekt pull request #37
Opened 2021-03-31 17:02 UTC by lucabloe

## Bereich

* Frontend

## Typ

* Testfinding / Bug

## Code Review
- [ ] @NimsaJ150 / @jonathan112358

## Funktionale Review
- [ ] @tomhinzmann 

## Anmerkungen

2021-04-08 08:31 UTC, NimsaJ150 requested changes
Hey, wäre super, wenn ihr nochmal drüber schauen könntet. Bei getFeatures() im component-editor.js fehlt noch der docstring. :)

2021-04-08 08:31 UTC, NimsaJ150 commented on docu/Repository.md
>  Die `core.py` ist die "Task Engine", die jegliche Logik enthält und Datenflüsse managed. Von hier werden alle Datenbank
Besser wenn das auch zu Z.35 sortiert wird oder?

2021-04-08 08:31 UTC, NimsaJ150 commented on frontend/static/js/component-editor.js
>  //Base url to distinguish between localhost and production environment
```suggestion
// Base url to distinguish between localhost and production environment
```

2021-04-08 08:31 UTC, NimsaJ150 commented on frontend/static/js/component-editor.js
>              const categories = data['categories'];
Unused constant categories -> wird diese irgendwo verwendet?

2021-04-08 08:31 UTC, NimsaJ150 commented on frontend/static/js/dashboard-renderer.js
>  function loadData() {
Macht init als Name wie bei dem component-editor Sinn?

2021-04-08 08:31 UTC, NimsaJ150 commented on frontend/static/js/dashboard-renderer.js
> +}
```suggestion
}

```

2021-04-08 08:31 UTC, NimsaJ150 commented on frontend/static/js/dashboard-renderer.js
> +// Check if component has been created/edited successfully
```suggestion
// Check if component has been deleted successfully
```

2021-04-08 08:31 UTC, NimsaJ150 commented on frontend/static/js/dashboard-renderer.js
> +        // Component has been created/edited successfully
```suggestion
        // Component has been deleted successfully
```

2021-04-08 08:31 UTC, NimsaJ150 commented on frontend/static/js/dashboard-renderer.js
> +        // Component has not been created/edited successfully
```suggestion
        // Component has not been deleted successfully
```

2021-04-08 08:31 UTC, NimsaJ150 commented on frontend/static/js/helper.js
> +     * @param {string} data_json: The JSON Object to be passed to the backend
Hat ein get Request überhaupt Daten, die gesendet werden können oder würde das einen Fehler werfen, weil es dann ja ein POST Request wäre?

2021-04-08 08:31 UTC, NimsaJ150 commented on frontend/static/js/helper.js
> +}
```suggestion
}

```

2021-04-08 08:31 UTC, NimsaJ150 commented on frontend/templates/index.html
> +</div>
Die Einrückungen passen nicht ganz, bitte nochmal drüber schauen

2021-04-10 14:20 UTC, lucabloe commented on frontend/static/js/helper.js
> +     * @param {string} data_json: The JSON Object to be passed to the backend
Stimmt, ich habe das Datenparameter entfernt, danke für den Hinweis.

2021-04-10 14:30 UTC, lucabloe commented
Hi @NimsaJ150 ,
ich habe die Bemerkungen jetzt eingearbeitet.

2021-04-10 14:36 UTC, NimsaJ150 commented on frontend/static/js/helper.js
> +            xhttp.send(data_json);
Vielen Dank! Muss das hier auch noch raus, weil data_json nicht mehr gefunden wird?

2021-04-10 14:37 UTC, NimsaJ150 commented
<img width="1020" alt="Screenshot at Apr 10 16-35-52" src="https://user-images.githubusercontent.com/44087726/114273588-f37fd380-9a1a-11eb-9c95-73d789bb417c.png">

Hat es das durch den merge jetzt irgendwie kaputt gemacht?

2021-04-11 00:24 UTC, NimsaJ150 commented
Geschlossen wegen cleanup auf 212

2021-04-11 00:24 UTC, closed without merging