223: metric_update
Praxisprojekt2021/praxisprojekt pull request #41
Opened 2021-04-02 16:09 UTC by jonathan112358

## Bereich
* Backend
   - Database-Handler

## Typ
* Feature

## Code Review
- [ ] @NimsaJ150

## Funktionale Review
- [ ] @Timo-Buecher 

## Anmerkungen
Zusätzliche Vorschläge wurden auf euren Hinweis hin entfernt. In diesem Branch sind nur noch die Aufgaben und keine eigenen Ideen.
P.S. Das Problem mit dem Speichern hatte nichts mit meinem Code zu tun, sondern weil jemand in der Datenbank doppelte Metriken ergänzt hat.

2021-04-02 16:55 UTC, Timo-Buecher requested changes

2021-04-02 16:55 UTC, Timo-Buecher commented on database/handler/metric_handler.py
>      return metrics_data_dict
throws error, return value does not exists

2021-04-02 21:29 UTC, Timo-Buecher requested changes
Bei mir nicht lauffähig wegen Import Fehlern. Habe diverse Wege ausprobiert, @NimsaJ150 ggf. hast du ja einen Vorschlag. Bis dahin kann ich nicht approven. Der Syntaxfehler ist aber jetzt behoben.

2021-04-02 23:15 UTC, NimsaJ150 commented
Ich habe die Imports alle mal gefixt, dürfte aber leider aktuell nur auf den 211 er Branch sein, im Zweifel den mal rein mergen. Ansonsten habe ich das get_metrics_data ausgeführt bekommen und das Format passt. @Timo-Buecher

2021-04-02 23:18 UTC, NimsaJ150 approved these changes

2021-04-03 07:22 UTC, jonathan112358 commented
> Bei mir nicht lauffähig wegen Import Fehlern. Habe diverse Wege ausprobiert, @NimsaJ150 ggf. hast du ja einen Vorschlag. Bis dahin kann ich nicht approven. Der Syntaxfehler ist aber jetzt behoben.

Das hat doch aber nichts mit dem Branch oder meinen Änderungen zu tun.

2021-04-03 08:49 UTC, Timo-Buecher approved these changes
Eigentlich würde ich nicht approven, da wir jetzt einen Fehler auf den Master mergen. (Auch wenn du den nicht produziert hast Jonathan). Da aber dieser Fehler in 211 gefixt wird und gleichzeitig 211 die einzige Funktion beinhaltet die get_metrics_data aufruft sollte es in dem Fall ok sein zu mergen.

2021-04-03 08:49 UTC, merged