201 get process and process list
Praxisprojekt2021/praxisprojekt pull request #44
Opened 2021-04-07 18:27 UTC by jonathan112358

## Bereich
* Backend
   - Database-Handler
* Database

## Typ
* Feature

## Code Review
- [ ] @NimsaJ150 / @sascha7777

## Funktionale Review
- [ ] @Timo-Buecher  / @Antonio1730

2021-04-07 20:42 UTC, Timo-Buecher requested changes
Ist funktional korrekt, bis auf die eine Anmerkung. Beim testen ist mir aufgefallen, dass im Core noch Änderungen anstehen, damit alles richtig funktioniert. Das machen aber @Sofie273 und @AaronDesler, daher kann der Code aus meiner Sicht auf den Master wenn die eine Zeile angepasst wurde.

2021-04-07 20:42 UTC, Timo-Buecher commented on database/handler/process_handler.py
> +    process_dict = get_process({"uid": uid})
Besser die Metriken aus dem input_dict ziehen, denn sonst werden nur die bestehenden Metriken geupdatet, neue Beziehungen zu Metriken werden aber nicht angelegt. Es wäre aber wichtig, dass auch im nachhinein neue Soll-Werte vergeben werde können, daher bitte input_dict nutzen.

Das wurde wahrscheinlich aus dem Component Handler übernommen, dort ist mir das auch schon aufgefallen und habe das auf meinem Branch schon korrigiert. Hier war es aber bisher kein Problem da man eine Komponente nur anlegen konnte wenn alle Metriken ausgefüllt waren und es keine Möglichkeit gab neue Metriken für die Komponente auszufüllen.

2021-04-07 20:42 UTC, Timo-Buecher commented on create_metrics.py
> +# print(ph.delete_process({"uid": "888e123ce5454a9aaf6dc1bb1d190513"}))
Nächstes mal bitte sowas aufräumen, oder am besten eine extra Test Datei nutzen und nicht die Datei missbrauchen 🤕

2021-04-08 05:36 UTC, jonathan112358 commented on database/handler/process_handler.py
> +    process_dict = get_process({"uid": uid})
Pass ich gleich an. Das ist uns beim Testen auch aufgefallen, aber wir dachten ehrlicherweise das soll so sein und man kann nur beim Erstellen Metriken hinzufügen.

2021-04-08 05:40 UTC, jonathan112358 commented on create_metrics.py
> +# print(ph.delete_process({"uid": "888e123ce5454a9aaf6dc1bb1d190513"}))
Hat die Datei einen Zweck ausser Testen?

2021-04-08 07:53 UTC, jonathan112358 commented on database/handler/process_handler.py
> +    process_dict = get_process({"uid": uid})
Ich habe mir die Funktion vor dem Hintergrund deiner Bitte gerade nochmal angeguckt und nun Gesprächsbedarf. Ich kann das so blind anpassen, aber letztendlich ist die Funktionalität meiner Auffassung nach damit nicht gegeben. Denn wenn ich die Funktion einfach anpasse indem ich die Info aus dem input_dict ziehe kann ich zwar neue Relationships dynamisch hinzufügen, allerdings fehlt uns der Test Metriken zu löschen, sollten diese nicht mehr vorhanden sein.

Overall bedeutet das für mich, dass wir im Grunde nur einen halben Job machen, da wir "addieren" unterstützen, aber kein "subtrahieren". Sollte das also eine Anforderung sein würde ich dafür plädieren beide Sachen umzusetzen? Würde mich über eine kurze Rückmeldung freuen bevor ich hier die neue Version pushe und dann weitere Änderungen notwendig sind. LG

2021-04-08 08:38 UTC, Timo-Buecher commented on create_metrics.py
> +# print(ph.delete_process({"uid": "888e123ce5454a9aaf6dc1bb1d190513"}))
Ja, über die Datei sollen die Metriken neuangelegt werden können, also wenn jemand die DB mal löscht soll er einfach diese Datei aufrufen können und alles ist wieder richtig.

Später kommen ggf. noch andere weitere Funktionen hinzu um unsere Software quasi zu initialisieren.

2021-04-08 12:15 UTC, NimsaJ150 commented
Bei mir werden für die Komponenten innerhalb des Prozesses noch nicht das "weight" zurückgegeben. Könnt ihr da bitte nochmal nachschauen, dass das passt und enthalten ist? :)

2021-04-08 13:58 UTC, NimsaJ150 approved these changes

2021-04-08 14:19 UTC, Timo-Buecher approved these changes

2021-04-08 14:20 UTC, merged