95: Erste processing Funktion
Praxisprojekt2021/praxisprojekt pull request #5
Opened 2021-03-10 12:33 UTC by sascha7777

## Bereich

* Backend
   - Logik

## Typ

* Testfinding / Bug

## Code Review
- [ ] @JonathanFreydank 

## Funktionale Review
- [ ] @NimsaJ150 

## Anmerkungen

2021-03-10 18:36 UTC, NimsaJ150 requested changes

2021-03-10 18:36 UTC, NimsaJ150 commented on processing/processing.py
> +def addition(summand1: float, summand2: float) -> float:
```suggestion
def addition(summand1: float, summand2: float) ->  Dict[str, float]:
```

Der typehint passt nicht ganz, vielleicht so wie oben? (dann fehlt noch ein "from typing import Dict")

2021-03-10 20:49 UTC, NimsaJ150 approved these changes
Danke :)

2021-03-11 09:35 UTC, JonathanFreydank approved these changes

2021-03-11 09:36 UTC, merged