90: front-end view
Praxisprojekt2021/praxisprojekt pull request #9
Opened 2021-03-13 21:26 UTC by twonkos

## Bereich

* Frontend

## Typ
* Feature
* Design

## Code Review
- [ ] @NimsaJ150 / @JonathanFreydank

## Funktionale Review
- [ ] @tomhinzmann 

## Anmerkungen

2021-03-13 22:05 UTC, NimsaJ150 requested changes
Das file sollte bitte im Ordner frontend/templates liegen :)

2021-03-13 22:23 UTC, twonkos commented
> Das file sollte bitte im Ordner frontend/templates liegen :)

Ist verschoben

2021-03-13 22:58 UTC, NimsaJ150 approved these changes

2021-03-13 22:59 UTC, NimsaJ150 commented
Bitte nächstes Mal dran denken: Kein Inline CSS! Keine Klassennamen zu Klassen, die nicht existieren!

2021-03-14 07:08 UTC, JonathanFreydank approved these changes
Code sieht für mich fein aus. Ich musste noch einen merge request bearbeiten, da Sofies index.html vorher gemergt wurde... Kann sein, dass Jasmin erst danach approved hat, oder nicht die aktuelle Version gezogen wurde. Sollten wir drauf achten.

2021-03-14 07:08 UTC, merged